### ISSUE TITLE
Not able to use Flexslider in Col's

### ISSUE THREAD

**Issue by wundrkind** [laxap/bootstrap_grids#1]
Hey there! Ive been using your extension for a while and noticed that when using the Flexslider Element in a Col Element, its not receiving a proper call i.e. its just using a almost empty script - tag. It'd be awesome if you could take a look at it. Thanks!

![flex_bug](https://cloud.githubusercontent.com/assets/12987258/8300764/88e6b480-1988-11e5-9047-63c871b771f4.jpg)

PS: Its working fine if I don't use the flexslider it in a column container though.

**Comment by sirdiego** [comment]
Hey, we also found this problem with Extbase plugins which are cachable. Non-cachable plugins work like a charm. We found that the problem is with the "insertData = 1" option, because the wrap replaces all {...} with "nothing". See: https://github.com/laxap/bootstrap_grids/blob/master/Configuration/TypoScript/setup.txt#L20

In our example the __trustedProperties were destroyed form this error.

**Comment by laxap** [comment]
The bug was known but I thought it was a problem of ext:gridelements. But after changing wrap/insertData to dataWrap adding a slider element worked. Please check if it works with the latest version 1.1.2.
https://github.com/laxap/bootstrap_grids/blob/master/Configuration/TypoScript/setup.txt#L19
