### ISSUE TITLE
Templates not found

### ISSUE THREAD

**Issue by afineske** [laxap/bootstrap_grids#45]
Hi,
i have a problem with boostrap_grid on Typo3 9.5.9.
![image](https://user-images.githubusercontent.com/11649139/63511210-dcf0d580-c4e0-11e9-8d33-6b26832463c8.png)
After installation gridelements and bootstrap_grids i create an tab4 element and got this error.
What going wrong here?

Best regards Andreas

**Comment by KodiakWeb** [comment]
Same here. None of the templates is found, because there are no templates.
It should use the flexforms, but it doesn't want to.

But I have no idea why.

Someone help please. :)

**Comment by KodiakWeb** [comment]
Alright, I was able to fix it. 
In my case there was an other template included (fluid_bootstrap_grids), because I tested this first.
After removing this template and clearing the cache it works fine.

So maybe you also have a template included, which destroys the bootstrap_grids.
You could also try changing the order of the included templates. :)

**Comment by afineske** [comment]
Thanks for the hint, im my case i have used the **Gridelements w/DataProcessing (recommended) (gridelements)** Template. After switching to **Gridelements (gridelements) [EXT:gridelements/Configuration/TypoScript/]** it works fine.

**Comment by laxap** [comment]
https://github.com/laxap/bootstrap_grids/releases/tag/2.2.0
