### ISSUE TITLE
Wrong display result for accordion

### ISSUE THREAD

**Issue by codexdb** [laxap/bootstrap_grids#9]
If you put a multi column element in an accordion, e.g. with different sizes, the result will be dispayed as one column.

E.g.: 
Create content full width, accordion full width.
Place inside accordion 2 col element with 75% width first col and 25% width second col for all screen sizes
Place inside each col content elements of your choice.
The result shows col 1 below and not beside col 2.

**Comment by laxap** [comment]
I tested it with version 1.2.0 and 1.3.0 and it worked here. (TYPO3 7.6.x)

**Comment by metiny** [comment]
The problem is, that classes are not added to the code when using e.g. cols2 inside accordion

I tested it with TYPO3 7.6.13
bootstrap_core 1.28
gridelements 7.0.5
bootstrap_grids 1.3.1
bootstrap_links 0.6.0
bsdist 1.3.3

a working solution from Pascal is here:
https://forge.typo3.org/issues/72057

Other grids do not work in the accordion grid by default.
You may change it to support grids but then you'll have to set the headers of the content elements in the accordion to hidden. Otherwise the titles are also shown in the accordion element panel.
Change it to use a reference to tt_content:

tt_content.gridelements_pi1.20.10.setup.accordion.columns.101.renderObj.20 =< tt_content

I tested it with TYPO 7.6.13 and it works.
